export const expenseCategories = [
  { label: "Food", value: "food", description: "Daily expenses for food and groceries" },
  { label: "Rent", value: "rent", description: "Monthly rent or housing costs" },
  { label: "Utilities", value: "utilities", description: "Monthly utility bills (electricity, water, etc.)" },
  { label: "Transportation", value: "transportation", description: "Daily commuting and transportation expenses" },
  { label: "Entertainment", value: "entertainment", description: "Costs for leisure and entertainment activities" },
  { label: "Healthcare", value: "healthcare", description: "Medical and healthcare expenses" },
  { label: "Education", value: "education", description: "Educational expenses, including tuition" },
  { label: "Groceries", value: "groceries", description: "Regular grocery shopping expenses" },
  { label: "Dining Out", value: "dining-out", description: "Costs of dining out at restaurants" },
  { label: "Clothing", value: "clothing", description: "Expenses related to clothing and apparel" },
  { label: "Home Repairs", value: "home-repairs", description: "Costs for home repairs and maintenance" },
  { label: "Travel", value: "travel", description: "Expenses related to travel and vacations" },
  { label: "Gifts", value: "gifts", description: "Costs of buying gifts for others" },
  { label: "Subscriptions", value: "subscriptions", description: "Monthly subscription service expenses" },
  { label: "Insurance", value: "insurance", description: "Insurance premium payments" },
  { label: "Taxes", value: "taxes", description: "Taxes and government fee payments" },
  { label: "Hobbies", value: "hobbies", description: "Expenses related to hobbies and interests" },
  { label: "Charity", value: "charity", description: "Expenses for charitable donations" },
  { label: "Pet Care", value: "pet-care", description: "Costs for pet care and supplies" },
  { label: "Savings", value: "savings", description: "Expenses allocated for savings and investments" },
  { label: "Fitness", value: "fitness", description: "Gym memberships and fitness-related expenses" },
  { label: "Phone Bill", value: "phone-bill", description: "Monthly phone and internet bills" },
  { label: "Car Maintenance", value: "car-maintenance", description: "Car maintenance and repair costs" },
  { label: "Home Decor", value: "home-decor", description: "Expenses for home decoration and furnishings" },
  { label: "Electronics", value: "electronics", description: "Expenses related to electronic gadgets and appliances" },
  { label: "Books", value: "books", description: "Expenses for books and reading materials" },
  { label: "Movies", value: "movies", description: "Costs of movie tickets and streaming services" },
];
