export const incomeCategories = [
  { label: "Salary", value: "salary", description: "Income from your regular job or salary" },
  { label: "Freelance", value: "freelance", description: "Income from freelance work or side gigs" },
  { label: "Investments", value: "investments", description: "Income from investments, stocks, or dividends" },
  { label: "Rental", value: "rental", description: "Income from renting out property or assets" },
  { label: "Business", value: "business", description: "Income from your own business or entrepreneurship" },
  { label: "Consulting", value: "consulting", description: "Income from consulting services" },
  { label: "Royalties", value: "royalties", description: "Income from book, music, or art royalties" },
  { label: "Online Sales", value: "online-sales", description: "Income from online product or service sales" },
  { label: "Real Estate", value: "real-estate", description: "Income from real estate transactions" },
  { label: "Commissions", value: "commissions", description: "Income from sales commissions" },
  { label: "Dividends", value: "dividends", description: "Income from dividend payments" },
  { label: "Grants", value: "grants", description: "Income from research or project grants" },
  { label: "Interest", value: "interest", description: "Income from interest on savings or investments" },
  { label: "Pension", value: "pension", description: "Income from pension or retirement plans" },
  { label: "Savings", value: "savings", description: "Income from savings or emergency funds" },
  { label: "Part-time Job", value: "part-time-job", description: "Income from part-time employment" },
  { label: "Inheritance", value: "inheritance", description: "Income from inheritance or gifts" },
  { label: "Hobbies", value: "hobbies", description: "Income from hobbies or crafts" },
  { label: "Online Courses", value: "online-courses", description: "Income from online course sales" },
  { label: "Teaching", value: "teaching", description: "Income from teaching or tutoring" },
];
